### ISSUE TITLE
Unrecognized function or variable 'nullZ'.

### ISSUE THREAD

**Issue by MicTott** [philjrdb/RegressionSim#1]
Hi all was just trying out this **dFF_simulation.m** and ran into this issue below. A google search didn't pull up anything for the "nullZ" function so not sure where it comes from. 

```
Unrecognized function or variable 'nullZ'.

Error in dFF_simulation (line 275)
    nullZ_neural_component = nullZ(neural_component);
```

**Comment by philjrdb** [comment]
Our bad - we've added nullZ function to the repository.
